import { AIMessage } from '@langchain/core/messages'
import { copyAgentNode } from './copy-agent'
import { visualAgentNode } from './visual-agent'
import { videoAgentNode } from './video-agent'
import { audioAgentNode } from './audio-agent'
import { avatarAgentNode } from './avatar-agent'
import { establishDirection, briefWave, reviewWave, finalReview } from './creative-director'
import { planAssetIdOf } from './_deps'
import { createAsset } from '@/lib/supabase/db'
import type { LangGraphRunnableConfig } from '@langchain/langgraph'
import type { ContentState } from '@/agent/state'
import type { Asset, AssetType } from '@/types/asset'
import type { PlanAsset } from '@/types/plan'
import type { AssetBrief } from '@/types/director'

/**
 * Each asset type is generated by one agent. Agents accept the explicit subset of
 * plan-assets for the current wave and read already-generated upstream assets from
 * `state.assets` to resolve their dependencies (first-frame image, voice, script).
 * They also read their per-asset brief from `state.assetBriefs[planAsset.id]`.
 */
const AGENTS: Record<
  AssetType,
  (
    state: typeof ContentState.State,
    planAssets: PlanAsset[]
  ) => Promise<Partial<typeof ContentState.State>>
> = {
  text: copyAgentNode,
  image: visualAgentNode,
  video: videoAgentNode,
  audio: audioAgentNode,
  avatar: avatarAgentNode,
}

/** Each weak/failed asset gets at most this many director-driven correction re-runs. */
const MAX_CORRECTIONS_PER_ASSET = 1

/**
 * Topologically sort the plan's assets into dependency "waves". Assets in the
 * same wave have no dependency on each other and run in parallel; each wave waits
 * for every previous wave to finish (so a video's first-frame image, or an
 * avatar's voice + image, are ready before it runs).
 *
 * Defensive rule: any non-text asset that declares no dependencies implicitly
 * depends on every text/script asset, guaranteeing the Script is produced first
 * even if the planner forgets to wire it.
 */
export function computeWaves(assets: PlanAsset[]): PlanAsset[][] {
  const byId = new Map(assets.map((a) => [a.id, a]))
  const textIds = assets.filter((a) => a.type === 'text').map((a) => a.id)

  const depsOf = (a: PlanAsset): string[] => {
    const declared = (a.dependencies ?? []).filter((d) => byId.has(d) && d !== a.id)
    if (declared.length > 0) return declared
    if (a.type !== 'text') return textIds.filter((id) => id !== a.id)
    return []
  }

  const level = new Map<string, number>()
  const computing = new Set<string>()

  const resolve = (a: PlanAsset): number => {
    if (level.has(a.id)) return level.get(a.id)!
    // Cycle guard: treat an asset currently being resolved as level 0.
    if (computing.has(a.id)) return 0
    computing.add(a.id)
    const deps = depsOf(a)
    const lvl = deps.length === 0 ? 0 : 1 + Math.max(...deps.map((d) => resolve(byId.get(d)!)))
    computing.delete(a.id)
    level.set(a.id, lvl)
    return lvl
  }

  assets.forEach(resolve)

  const maxLevel = Math.max(0, ...Array.from(level.values()))
  const waves: PlanAsset[][] = []
  for (let i = 0; i <= maxLevel; i++) {
    const wave = assets.filter((a) => level.get(a.id) === i)
    if (wave.length > 0) waves.push(wave)
  }
  return waves
}

const TYPE_LABEL: Record<AssetType, { singular: string; plural: string }> = {
  text: { singular: 'the script', plural: 'the script' },
  image: { singular: 'the first-frame image', plural: 'first-frame images' },
  audio: { singular: 'the voiceover', plural: 'the voiceovers' },
  video: { singular: 'the video', plural: 'the videos' },
  avatar: { singular: 'the talking avatar', plural: 'the talking avatars' },
}

function describeWave(wave: PlanAsset[]): string {
  const counts = new Map<AssetType, number>()
  for (const a of wave) counts.set(a.type, (counts.get(a.type) ?? 0) + 1)
  const parts = Array.from(counts.entries()).map(([type, n]) =>
    n === 1 ? TYPE_LABEL[type].singular : `${n} ${TYPE_LABEL[type].plural}`
  )
  const list =
    parts.length <= 1
      ? parts.join('')
      : `${parts.slice(0, -1).join(', ')} and ${parts[parts.length - 1]}`
  const action = wave.some((a) => a.type === 'text') ? 'Writing' : 'Generating'
  return `${action} ${list}${parts.length > 1 ? ' in parallel' : ''}…`
}

/** Run the given plan-assets through their agents (grouped by type, in parallel). */
async function runAgents(
  waveState: typeof ContentState.State,
  planAssets: PlanAsset[]
): Promise<{ assets: Asset[]; cost: number }> {
  const byType = new Map<AssetType, PlanAsset[]>()
  for (const a of planAssets) {
    const list = byType.get(a.type) ?? []
    list.push(a)
    byType.set(a.type, list)
  }
  const results = await Promise.all(
    Array.from(byType.entries()).map(([type, subset]) => AGENTS[type](waveState, subset))
  )
  let assets: Asset[] = []
  let cost = 0
  for (const r of results) {
    if (r.assets?.length) assets = [...assets, ...r.assets]
    cost += r.actualCost ?? 0
  }
  return { assets, cost }
}

async function persistAssets(assets: Asset[]): Promise<void> {
  const results = await Promise.allSettled(
    assets.map((asset) =>
      createAsset({
        project_id: asset.project_id,
        plan_id: asset.plan_id,
        type: asset.type,
        name: asset.name,
        description: asset.description,
        status: asset.status,
        storage_path: asset.storage_path,
        public_url: asset.public_url,
        specs: asset.specs,
        provider: asset.provider,
        model: asset.model,
        estimated_cost: asset.estimated_cost,
        actual_cost: asset.actual_cost,
        metadata: asset.metadata,
      })
    )
  )
  results.forEach((r, i) => {
    if (r.status === 'rejected') {
      console.error(`[Supervisor] Failed to persist asset "${assets[i]?.name}":`, r.reason)
    }
  })
}

export async function supervisorNode(
  state: typeof ContentState.State,
  config?: LangGraphRunnableConfig
): Promise<Partial<typeof ContentState.State>> {
  const plan = state.plan!
  const total = plan.assets.length

  // Human-readable, real-time status line — sent as a 'custom' stream event and
  // surfaced verbatim in the chat UI (see src/lib/stream-adapter.ts).
  const emitPhase = (phase: string) => config?.writer?.({ phase })

  // ── The director sets the global creative anchor before any asset is made. ──
  emitPhase('Setting the creative direction…')
  const direction = await establishDirection(state)
  const styleBrief = direction.styleBrief
  let directorContext = direction.directorContext

  const waves = computeWaves(plan.assets)

  // Accumulate generated assets so each wave can resolve dependencies produced by
  // earlier waves. assetBriefs accumulates the director's per-asset instructions.
  let accumulated: Asset[] = [...state.assets]
  const assetBriefs: Record<string, AssetBrief> = { ...state.assetBriefs }
  let totalCost = 0

  for (const wave of waves) {
    const baseState = { ...state, styleBrief, assets: accumulated, assetBriefs }

    // 1) Director briefs each asset in the wave (it has seen earlier waves).
    emitPhase('Briefing the team…')
    const briefs = await briefWave(baseState, wave, directorContext)
    for (const b of briefs) assetBriefs[b.planAssetId] = b

    // 2) Agents execute the wave in parallel, each reading its brief from state.
    emitPhase(describeWave(wave))
    const runState = { ...state, styleBrief, assets: accumulated, assetBriefs }
    const run = await runAgents(runState, wave)
    let produced = run.assets
    totalCost += run.cost

    // 3) Director reviews the wave and flags weak/failed assets.
    emitPhase('Reviewing the wave…')
    const review = await reviewWave(baseState, wave, produced, briefs, directorContext)
    directorContext = review.directorContext
    const verdictById = new Map(review.verdicts.map((v) => [v.planAssetId, v]))

    // 4) Per-asset correction: re-run ONLY the assets that missed, bounded.
    for (const planAsset of wave) {
      const current = produced.find((a) => planAssetIdOf(a) === planAsset.id)
      const verdict = verdictById.get(planAsset.id)
      const needsFix = current?.status === 'failed' || verdict?.pass === false
      if (!needsFix) continue

      const errMsg = String((current?.metadata as Record<string, unknown>)?.error ?? '')
      const correction = verdict?.feedback ?? errMsg ?? ''
      const correctionNote = correction || 'Asset did not meet the brief — redo it more faithfully.'

      for (let attempt = 0; attempt < MAX_CORRECTIONS_PER_ASSET; attempt++) {
        emitPhase(`Correcting ${planAsset.name}…`)
        assetBriefs[planAsset.id] = {
          ...(assetBriefs[planAsset.id] ?? { planAssetId: planAsset.id, instruction: planAsset.description }),
          correction: correctionNote,
        }
        const fixState = { ...state, styleBrief, assets: accumulated, assetBriefs }
        const redo = await runAgents(fixState, [planAsset])
        totalCost += redo.cost
        if (redo.assets.length > 0) {
          // Replace the weak asset with the corrected one.
          produced = produced.filter((a) => planAssetIdOf(a) !== planAsset.id)
          produced = [...produced, ...redo.assets]
        }
        const fixed = produced.find((a) => planAssetIdOf(a) === planAsset.id)
        if (fixed?.status === 'completed') break
      }
    }

    accumulated = [...accumulated, ...produced]

    // 5) Persist this wave's assets so a later crash doesn't lose finished work.
    emitPhase('Saving your assets…')
    await persistAssets(produced)
  }

  // Only the assets generated in this run (exclude any pre-existing state.assets).
  const generated = accumulated.slice(state.assets.length)

  // ── The director owns the final holistic verdict. ──
  emitPhase('Final review…')
  const reviewResult = await finalReview({ ...state, styleBrief }, generated, directorContext)

  const completed = generated.filter((a) => a.status === 'completed').length
  const failed = generated.filter((a) => a.status === 'failed').length

  return {
    assets: generated,
    actualCost: totalCost,
    styleBrief,
    assetBriefs,
    directorContext,
    reviewResult,
    status: completed > 0 ? 'completed' : 'failed',
    generationProgress: { total, completed, failed, current: null },
    messages: [
      new AIMessage(
        `Generation complete: ${completed}/${total} assets created successfully.${
          failed > 0 ? ` ${failed} failed.` : ''
        } Quality score: ${reviewResult.overallScore}/100.`
      ),
    ],
  }
}
